### ISSUE TITLE
Instagram icon & link are missing 

### ISSUE THREAD

**Issue by geekloper** [Al-Fihriya-Academy/about-us#1]
In contact section instagram icon and url are missing. The link is ( https://www.instagram.com/alfihriyaacademy/ )

![image](https://user-images.githubusercontent.com/16905576/84397924-8daa9b80-abff-11ea-967d-2647313918b7.png)

**Comment by geekloper2** [comment]
Rani khedam fiha wach n9der nkhdem 3liha
