### ISSUE TITLE
Add contact form to contact us via email

### ISSUE THREAD

**Issue by youssef123698745** [Al-Fihriya-Academy/about-us#11]
Salam 3ndi ouahd lfikra 3lach mankadouch contact nta3na bla maymchich l facebook bach idir contact  nkado contact fih : Non Prénom Gmail ... oul message  lygi imch lgmail nta3 site ntmna ana lfikra ouslat

**Comment by geekloper** [comment]
@hbourbouh chnu banlek ? Kayna chi email khass b lgroup bach @youssef123698745  ykhdem 3la had la partie ?

**Comment by geekloper** [comment]
@youssef123698745  Ay haja dial CSS khdam b library li khdamin biha adi nkhelilek link lte7t. 
Haka bach n7awlou ma2amkan l code dialna ykoun mfhoum 👍  👍 

[https://bulma.io/documentation](https://bulma.io/documentation)

**Comment by youssef123698745** [comment]
واخا ان شاء الله  غد نخدم عليها و gmail من بعد غد نكول لعموم موافق يه او لا

**Comment by hbourbouh** [comment]
Hada howa email
alfihriya.academy@gmail.com

**Comment by youssef123698745** [comment]
ok Merci
