### ISSUE TITLE
align columns vertically 

### ISSUE THREAD

**Issue by AitoApps** [Al-Fihriya-Academy/about-us#28]
salam  kayna hade class [https://bulma.io/documentation/columns/options/#vertical-alignment](url) **is-vcentered** ka dire dakchi li katgoul 😁  
hade image bla hade l class 
<img width="1234" alt="Screen Shot 2020-06-20 at 00 19 02" src="https://user-images.githubusercontent.com/6819197/85185879-e1675580-b28d-11ea-93c9-c66a4534b03d.png">

ou hadi mli kanzidha

<img width="1245" alt="Screen Shot 2020-06-20 at 00 19 40" src="https://user-images.githubusercontent.com/6819197/85185889-efb57180-b28d-11ea-91c1-b0f582d82c67.png">

ila ka tbane ahssan ndire pull request ou nzidha?

**Comment by geekloper** [comment]
DONE #29 👍
