### ISSUE TITLE
Courses link is broken

### ISSUE THREAD

**Issue by AyoubEd-zz** [Al-Fihriya-Academy/about-us#37]
**Issue:** the link in the header that points to the courses page leads to a 404 page.
**Possible fix:** change link in the button from "Courses.html" to all lowercase "courses.html".
**Difficulty:**  easy

If you want to work on the issue, manifest your interest bellow, the admins will assign you. Submit a pull request with this issue linked to it.

**Comment by Temo27anas** [comment]
interested

**Comment by Temo27anas** [comment]
//Fixed// https://github.com/Al-Fihriya-Academy/about-us/pull/42/commits/e47791910fa718b38d5e3356673b9dea8d25094a

**Comment by AyoubEd-zz** [comment]
#42
