### ISSUE TITLE
Courses containers difference of heights issue

### ISSUE THREAD

**Issue by AyoubEd-zz** [Al-Fihriya-Academy/about-us#44]
**Issue:** the containers don't have the same height and it looks weird.
**Possible fix:** maybe try using flexbox, grid CSS to display the grid.
**Difficulty**: easy

If you want to work on the issue, manifest your interest bellow, the admins will assign you. Submit a pull request with this issue linked to it.

![image](https://user-images.githubusercontent.com/20077848/85920840-7d3d2680-b877-11ea-9fab-4524d9e97939.png)

**Comment by OussamaTo** [comment]
Okey Thank You Mr Ayoub I will fix it

**Comment by AyoubEd-zz** [comment]
Awesome, looking forward to seeing the results

**Comment by Temo27anas** [comment]
i'll fix it

**Comment by Temo27anas** [comment]
FIXED https://github.com/Al-Fihriya-Academy/about-us/pull/47/commits/75ecde86e17b620bf59fc6018c2a8e4ad33e6bfe
